[project]
name = "dag-services"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "composio>=0.9.1",
    "langgraph>=1.0.2",
]
